### ISSUE TITLE
Pokemon X & Y Postgame Checklist

### ISSUE THREAD

**Issue by PhilMurwin** [PhilMurwin/PokemonChecklists#1]
- [ ] **Complete the Kalos Pokedex**
  - [ ] 150 Central Pokedex
  - [ ] 150 Costal Pokdex
  - [ ] 151 Mountain Pokedex
    - [ ] Capture Mewtwo (Located: Pokemon Village)
    - [ ] Capture Zygarde (Located: Terminus Cave - B3)
- [ ] **Locate & Capture Articuno, Zapdos *OR* Moltres**
  - [ ] Trade for Bird #2
  - [ ] Trade for Bird #3
- [ ] **Trade for Alt Version Legendary (Yveltal / Xerneas)**
- [x] **Receive Second Starter from Shauna (Vaniville)**
- [ ] **Catch All Available Pokemon in Friend Safaris**
  - [ ] .(12) Normal Type
  - [ ] .(12) Bug Type
  - [ ] .(12) Dark Type
  - [ ] .(7) Dragon Type
  - [ ] .(12) Electric Type
  - [ ] .(10) Fairy Type
  - [ ] .(11) Fighting Type
  - [ ] .(11) Fire Type
  - [ ] .(12) Flying Type
  - [ ] .(8) Ghost Type
  - [ ] .(11) Grass Type
  - [ ] .(11) Ground Type
  - [ ] .(11) Ice Type
  - [ ] .(12) Poison Type
  - [ ] .(11) Psychic Type
  - [ ] .(10) Rock Type
  - [ ] .(10) Steel Type
  - [ ] .(11) Water Type
- [ ] **Grand Duke/Duchess Ranking at Battle Chateau**
- [x] **Max-out your Style in Lumiose City**
  - [x] Collect All 16 O-Powers
  - [x] Collect "Hatching" O-Power in Lumiose City
- [x] **Final Rival Battle in Kiloude City**
- [ ] **Achieve Gold Trainer Card**
  - [x] Defeat the Elite Four
  - [ ] Complete Kalos Pokdex
  - [ ] Complete 1 Battle Maison Super Challenge
- [ ] **Take a Photograph at all Locations**
  - [ ] Anistar City
  - [ ] Aquacorde Town
  - [ ] Azure Bay
  - [ ] Couriway Town
  - [ ] Frost Cavern
  - [ ] Geosenge Town (Background changes depending on story progression)
  - [ ] Lumiose City
  - [ ] Parfum Palace
  - [ ] Pokemon League (Elite 4 Building)
  - [ ] Route 7
  - [ ] Shalour City
  - [ ] Snowbelle City
- [ ] **Purchase All Clothing**
  - [ ] Boys: 12 Accessories, 7 bags, 19 hats, 34 shirts, 14 shoes, 16 trousers
  - [ ] Girls: 24 Accessories, 16 bags, 44 bottoms, 9 dresses, 27 hats, 24 shoes, 26 shoes, 34 tops
- [ ] **Perfect Score at Restaurant Le Naw**
- [ ] **Perfect Scores at Restaurant Le Yeah**
  - [ ] Triple
  - [ ] Rotation
- [ ] **Perfect Scores at Restaurant Le Wow**
  - [ ] Double
  - [ ] Triple
  - [ ] Rotation
- [ ] **Perfect Scores at Sushi High Roller**
  - [ ] Double
  - [ ] Triple
  - [ ] Rotation
- [ ] **Collect & Mutate All Berries**  
  - See Berry List in comments below
- [ ] **Trade for all different Region Vivillon**
  - [ ] Archipelago
  - [ ] Continental
  - [ ] Elegant
  - [ ] Garden
  - [ ] High Plains
  - [ ] Icy Snow
  - [ ] Jungle
  - [ ] Marine
  - [ ] Modern
  - [ ] Monsoon
  - [ ] Meadow
  - [ ] Ocean
  - [ ] Polar
  - [ ] River
  - [ ] Sandstorm
  - [ ] Savannah
  - [ ] Sun
  - [ ] Tundra
  - [x] Event 1 (Pokeball)
  - [x] Event 2 (GTS)
- [ ] **Collect All Mega-Evolution Stones**
  - See Mega Stone List in comments below
- [ ] **Trade for Alt. Version Mega-Stones**
- [x] **Completed All Looker Missions**
  - [x] 1. "This Guy Is A Real...Looker"
  - [x] 2. "In the Back Alleys"
  - [x] 3. "Detective, Tourist, Gang"
  - [x] 4. "An Unforgivable Crime"
  - [x] 5. "A Fiery Woman & A Truth Revealed"
  - [x] 6. Here's looking at you kid"
- [ ] **Complete All Super Training Regimes**
- [ ] **Complete Secret Super Training Regimes**
  - [ ] Secret Super Training Lv. 1
  - [ ] Secret Super Training Lv. 2
- [ ] **Master Rank at Battle Institute Test**
- [ ] **Battle Maison Standard Challenges**
  - [ ] Single
  - [ ] Double
  - [ ] Triple
  - [ ] Rotation
  - [ ] Multi
- [ ] **Battle Maison Super Challenges**
  - [ ] Single
  - [ ] Double
  - [ ] Triple
  - [ ] Rotation
  - [ ] Multi
- [ ] **Collect All 100 Technical Machines (TMs)**
  - See TM List in comments below
- [ ] **Catch all Different Color Flabebe**
  - [ ] Red
  - [ ] Orange
  - [ ] Yellow
  - [ ] Blue
  - [ ] White

**Comment by PhilMurwin** [comment]
<sup>* Berry only available through mutation</sup>

Berry 1 | + Berry 2 | = Berry 3
-----------|-----------|--------------
[ ] Kelpsy | [ ] Wacan | [ ] Apicot
[ ] Aguav | [ ] Figy | [ ] Grepa
[ ] Aspear | [ ] Leppa | [ ] Hondew
[ ] Hondew* | [ ] Yache | [ ] Liechi
[ ] Qualot | [ ] Tanga | [ ] Ganlon
[ ] Liechi* | [ ] Ganlon* | [ ] Kee
[ ] Grepa | [ ] Roseli | [ ] Salac
[ ] Pomeg | [ ] Kasib | [ ] Petaya
[ ] Salac* | [ ] Petaya* | [ ] Maranga
[ ] Chesto | [ ] Persim | [ ] Kelpsy
[ ] Iapapa | [ ] Mago | [ ] Pomeg
[ ] Oran | [ ] Pecha | [ ] Qualot
[ ] Sitrus | [ ] Lum | [ ] Tamato
-----------|-----------|--------------
[ ] Cheri | [ ] Charti
[ ] Rawst | [ ] Haban
[ ] Wiki | [ ] Starf
[ ] Occa | [ ] Colbur
[ ] Passho | [ ] Babiri
[ ] Rindo | [ ] Chilan
[ ] Chople | [ ] Lansat
[ ] Kebia | [ ] Shuca

**Comment by PhilMurwin** [comment]
- [ ] Starter #2 (Vernal Ave)
- [ ] Starter #3 (Vernal Ave)
- [ ] Alakazam (Reflecting Cave B3)
- [ ] Gengar (Laverre City - Gift)
- [ ] Kangaskhan (Glittering Cave)
- [ ] Gyarados (Couriway Town)
- [ ] Aerodactyl (Ambrette Town - Gift)
- [ ] Ampharos (Azure Bay - Gift)
- [ ] Scizor (Frozen Cavern)
- [ ] Gardevoir (Traded Ralts - Lumiose)
- [ ] Mawile (shabboneau Castle)
- [ ] Medicham (Laverre City)
- [ ] Banette (Cave of Emptiness)
- [x] Absol (Kiloude City - Rival Battle)
- [ ] Garchomp (Victory Road)
- [ ] Abomasnow (Frozen Cavern - Gift)
- [ ] Charizard X (Vernal Ave)
- [ ] Charizard Y (Vernal Ave)
- [ ] Mewtwo X (Pokemon Village)
- [ ] Mewtwo Y (Pokemon Village)
- [ ] Heracross (Santalune Forest) - Y
- [ ] Houndoom (Route 16) - Y
- [ ] Aggron (Cyllage Gym) - Y
- [ ] Pinsir (Santalune Forest) - X
- [ ] Manectric (Route 16) - X
- [ ] Tyranitar (Cyllage Gym) - X

**Comment by PhilMurwin** [comment]
- [ ] Hone Claws
- [ ] Sludge Bomb
- [ ] Stone Edge
- [ ] Dragon Claws
- [ ] Sandstorm
- [ ] Volt Switch
- [ ] Psyshock
- [ ] Fire Blast
- [ ] Thunder Wave
- [ ] Calm Mind
- [ ] Rock Tomb
- [ ] Gyro Ball
- [ ] Roar
- [ ] Aerial Ace
- [ ] Sword Dance
- [ ] Toxic
- [ ] Torment
- [ ] Struggle Bug
- [ ] Hail
- [ ] Facade
- [ ] Psych up
- [ ] Bulk Up
- [ ] Flame Charge
- [ ] Bulldoze
- [ ] Venoshock
- [ ] Rest
- [ ] Frost Breath
- [ ] Hidden Power
- [ ] Attract
- [ ] Rock Slide
- [ ] Sunny Day
- [ ] Thief
- [ ] X-Scissor
- [ ] Taunt
- [ ] Low Sweep
- [ ] Dragon Tail
- [ ] Ice Beam
- [ ] Round
- [ ] Infestation
- [ ] Blizzard
- [ ] Echoed Voice
- [ ] Poison Jab
- [ ] Hyper Beam
- [ ] Overheat
- [ ] Dream Eater
- [ ] Light Screen
- [ ] Steel Wing
- [ ] Grass Knot
- [ ] Protect
- [ ] Focus Blast
- [ ] Swagger
- [ ] Rain Dance
- [ ] Energy Ball
- [ ] Sleep Talk
- [ ] Roost
- [ ] False Swipe
- [ ] U-Turn
- [ ] Safeguard
- [ ] Scald
- [ ] Substitute
- [ ] Frustration

**Comment by PhilMurwin** [comment]
This was my personal checklist until I wrote the web version.
